"""Matching engine: continuous double auction with observation builder.

Public API:

    engine = MatchingEngine()
    ack = engine.submit(actor_id, msg)        # PlaceLimit or Cancel
    events = engine.match_and_advance()       # expire TIF orders, bump step
    obs = engine.observation(actor_id, n=10)  # build a private Observation
    gt = engine.ground_truth_view(actor_id)   # harness-only: true account state

    step_events = engine.step(                # Step wrapper
        background_events=[(actor, msg), ...],
        agent_id="agent",
        agent_action=msg_or_none,
    )

Design invariants enforced:
- INV-1:  No scalar feedback signal of any kind.
- INV-9:  No randomness inside the engine (pure bookkeeping).
- INV-11: Observation never leaks ground-truth queue position or other
          actors' state; those are exposed ONLY through ground_truth_view().
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Final

from topos.contracts.market import (
    N_LEVELS,
    Ack,
    AckStatus,
    BookLevel,
    Cancel,
    ExchangeMessage,
    Fill,
    Liquidity,
    Observation,
    PlaceLimit,
    Side,
    Trade,
)
from topos.env.orderbook import OrderBook, RestingOrder


# ---------------------------------------------------------------------------
# Internal event types produced by the matching engine
# ---------------------------------------------------------------------------

@dataclass(frozen=True)
class EngineAck:
    """Engine-internal ack, tagged with actor_id for routing."""
    actor_id: str
    ack: Ack


@dataclass(frozen=True)
class EngineFill:
    """Engine-internal fill, tagged with actor_id for routing."""
    actor_id: str
    fill: Fill


@dataclass(frozen=True)
class EngineTrade:
    """A public trade print generated by matching."""
    trade: Trade


EngineEvent = EngineAck | EngineFill | EngineTrade


# ---------------------------------------------------------------------------
# Per-actor ground-truth account state (harness-only — INV-11)
# ---------------------------------------------------------------------------

@dataclass
class ActorAccount:
    """Ground-truth account for one actor.

    Exposed ONLY through ``ground_truth_view()`` — never through Observation.
    """
    inventory_lots: int = 0
    cash: int = 0  # integer: price_ticks * size_lots per fill
    fills: list[Fill] = field(default_factory=list)

    # map from actor-scoped order_id to the resting order
    open_orders: dict[int, RestingOrder] = field(default_factory=dict)


@dataclass(frozen=True)
class GroundTruthView:
    """Harness-only snapshot of an actor's true state (INV-11)."""
    actor_id: str
    inventory_lots: int
    cash: int
    open_order_ids: tuple[int, ...]
    fills: tuple[Fill, ...]


# ---------------------------------------------------------------------------
# The matching engine
# ---------------------------------------------------------------------------

_EMPTY_BIDS: Final[tuple[BookLevel, ...]] = tuple(
    BookLevel(price_ticks=0, size_lots=0) for _ in range(N_LEVELS)
)
_EMPTY_ASKS: Final[tuple[BookLevel, ...]] = tuple(
    BookLevel(price_ticks=0, size_lots=0) for _ in range(N_LEVELS)
)


class MatchingEngine:
    """Single-instrument limit order book engine.

    Supports multiple named actors, each with private order-id namespaces.
    Order types: PlaceLimit (GTC or tif_steps expiry) and Cancel.
    A marketable limit crosses immediately — no separate market-order type.

    The engine is pure bookkeeping: no randomness (INV-9), no feedback signal (INV-1).
    """

    def __init__(self) -> None:
        self._book = OrderBook()
        self._step: int = 0
        self._accounts: dict[str, ActorAccount] = {}
        self._next_internal_id: int = 0
        # Actor-scoped order-id counters
        self._actor_order_counters: dict[str, int] = {}

        # Events accumulated within the current step
        self._pending_events: list[EngineEvent] = []

        # Per-actor event buffers for observation building
        self._actor_acks: dict[str, list[Ack]] = {}
        self._actor_fills: dict[str, list[Fill]] = {}
        self._public_trades: list[Trade] = []

    # ------------------------------------------------------------------
    # Private helpers
    # ------------------------------------------------------------------

    def _ensure_actor(self, actor_id: str) -> ActorAccount:
        if actor_id not in self._accounts:
            self._accounts[actor_id] = ActorAccount()
            self._actor_acks[actor_id] = []
            self._actor_fills[actor_id] = []
            self._actor_order_counters[actor_id] = 0
        return self._accounts[actor_id]

    def _alloc_order_id(self, actor_id: str) -> int:
        oid = self._actor_order_counters[actor_id]
        self._actor_order_counters[actor_id] = oid + 1
        return oid

    def _emit_ack(self, actor_id: str, order_id: int, status: AckStatus) -> Ack:
        ack = Ack(order_id=order_id, status=status, step=self._step)
        self._actor_acks.setdefault(actor_id, []).append(ack)
        self._pending_events.append(EngineAck(actor_id=actor_id, ack=ack))
        return ack

    def _emit_fill(
        self, actor_id: str, order_id: int,
        price: int, size: int, liquidity: Liquidity,
    ) -> Fill:
        fill = Fill(
            order_id=order_id,
            price_ticks=price,
            size_lots=size,
            liquidity=liquidity,
            step=self._step,
        )
        self._actor_fills.setdefault(actor_id, []).append(fill)
        self._pending_events.append(EngineFill(actor_id=actor_id, fill=fill))

        # Update account
        acct = self._ensure_actor(actor_id)
        acct.fills.append(fill)
        if liquidity == Liquidity.MAKER:
            # Maker: the resting side
            side = self._book.get_order(actor_id, order_id)
            if side is not None:
                if side.side == Side.BUY:
                    acct.inventory_lots += size
                    acct.cash -= price * size
                else:
                    acct.inventory_lots -= size
                    acct.cash += price * size
            # If order is already gone (fully filled and removed), we need
            # the side info from the fill context — handled by caller.
        else:
            # Taker fills are handled by the submit path that knows the side
            pass
        return fill

    def _emit_trade(self, price: int, size: int, aggressor: Side) -> None:
        trade = Trade(price_ticks=price, size_lots=size, aggressor=aggressor)
        self._public_trades.append(trade)
        self._pending_events.append(EngineTrade(trade=trade))

    # ------------------------------------------------------------------
    # Public API: submit
    # ------------------------------------------------------------------

    def submit(self, actor_id: str, msg: ExchangeMessage) -> Ack:
        """Submit an order action from the given actor.

        Returns the primary Ack (ACCEPTED or REJECTED for PlaceLimit;
        CANCELED or REJECTED for Cancel).
        """
        self._ensure_actor(actor_id)

        if isinstance(msg, PlaceLimit):
            return self._submit_limit(actor_id, msg)
        elif isinstance(msg, Cancel):
            return self._submit_cancel(actor_id, msg)
        else:
            # Should be unreachable given ExchangeMessage type alias
            raise TypeError(f"Unknown message type: {type(msg)}")

    def _submit_limit(self, actor_id: str, msg: PlaceLimit) -> Ack:
        """Process a limit order: match aggressively, then rest remainder."""
        acct = self._accounts[actor_id]
        order_id = self._alloc_order_id(actor_id)

        # Accept the order
        accept_ack = self._emit_ack(actor_id, order_id, AckStatus.ACCEPTED)

        remaining = msg.size_lots

        # Try to match against the opposing side
        remaining = self._match_incoming(
            actor_id, order_id, msg.side, msg.price_ticks, remaining,
        )

        # Rest the remainder if any
        if remaining > 0:
            resting = self._book.make_resting_order(
                order_id=order_id,
                actor_id=actor_id,
                side=msg.side,
                price_ticks=msg.price_ticks,
                size_lots=remaining,
                tif_steps=msg.tif_steps,
                placed_step=self._step,
            )
            self._book.insert(resting)
            acct.open_orders[order_id] = resting

        return accept_ack

    def _match_incoming(
        self,
        taker_actor: str,
        taker_order_id: int,
        taker_side: Side,
        limit_price: int,
        remaining: int,
    ) -> int:
        """Match incoming order against the opposing book side.

        Returns the number of unfilled lots.  Emits fills and trades.
        """
        taker_acct = self._accounts[taker_actor]

        if taker_side == Side.BUY:
            # Match against asks (ascending price)
            opp_book = self._book._asks
        else:
            # Match against bids (descending price)
            opp_book = self._book._bids

        # We need to iterate levels in order and consume
        levels_to_clean: list[int] = []

        for price, level in list(opp_book.items()):
            if remaining <= 0:
                break

            # Price check: can we trade at this level?
            if taker_side == Side.BUY and price > limit_price:
                break  # asks are ascending; everything after is worse
            if taker_side == Side.SELL and price < limit_price:
                break  # bids are descending; everything after is worse

            # Match against orders at this level in FIFO order
            orders_to_remove: list[int] = []
            for seq, resting in list(level.orders.items()):
                if remaining <= 0:
                    break
                if resting.remaining_lots <= 0:
                    continue

                fill_size = min(remaining, resting.remaining_lots)
                fill_price = resting.price_ticks  # trade at resting price

                # Maker fill (resting order)
                maker_acct = self._accounts[resting.actor_id]
                maker_fill = Fill(
                    order_id=resting.order_id,
                    price_ticks=fill_price,
                    size_lots=fill_size,
                    liquidity=Liquidity.MAKER,
                    step=self._step,
                )
                self._actor_fills.setdefault(resting.actor_id, []).append(maker_fill)
                self._pending_events.append(EngineFill(actor_id=resting.actor_id, fill=maker_fill))
                maker_acct.fills.append(maker_fill)

                # Update maker account
                if resting.side == Side.BUY:
                    maker_acct.inventory_lots += fill_size
                    maker_acct.cash -= fill_price * fill_size
                else:
                    maker_acct.inventory_lots -= fill_size
                    maker_acct.cash += fill_price * fill_size

                # Taker fill
                taker_fill = Fill(
                    order_id=taker_order_id,
                    price_ticks=fill_price,
                    size_lots=fill_size,
                    liquidity=Liquidity.TAKER,
                    step=self._step,
                )
                self._actor_fills.setdefault(taker_actor, []).append(taker_fill)
                self._pending_events.append(EngineFill(actor_id=taker_actor, fill=taker_fill))
                taker_acct.fills.append(taker_fill)

                # Update taker account
                if taker_side == Side.BUY:
                    taker_acct.inventory_lots += fill_size
                    taker_acct.cash -= fill_price * fill_size
                else:
                    taker_acct.inventory_lots -= fill_size
                    taker_acct.cash += fill_price * fill_size

                # Trade print
                self._emit_trade(fill_price, fill_size, aggressor=taker_side)

                # Decrement resting order
                resting.remaining_lots -= fill_size
                remaining -= fill_size

                if resting.remaining_lots == 0:
                    orders_to_remove.append(seq)
                    # Remove from actor's open orders
                    maker_acct.open_orders.pop(resting.order_id, None)

            # Clean up fully filled orders from the level
            for seq in orders_to_remove:
                del level.orders[seq]

        return remaining

    def _submit_cancel(self, actor_id: str, msg: Cancel) -> Ack:
        """Cancel a resting order."""
        acct = self._accounts[actor_id]
        resting = acct.open_orders.get(msg.order_id)

        if resting is None or resting.remaining_lots <= 0:
            return self._emit_ack(actor_id, msg.order_id, AckStatus.REJECTED)

        # Remove from book
        self._book.remove(resting)
        del acct.open_orders[msg.order_id]
        return self._emit_ack(actor_id, msg.order_id, AckStatus.CANCELED)

    # ------------------------------------------------------------------
    # Public API: match_and_advance
    # ------------------------------------------------------------------

    def match_and_advance(self) -> list[EngineEvent]:
        """Expire TIF orders, advance the step counter, return events.

        Called once per step after all submissions for the step are done.
        """
        # Advance step first so TIF age uses the new step value.
        # An order with tif_steps=N placed at step S expires when
        # the step counter reaches S+N (i.e. after N full steps).
        self._step += 1

        # Expire orders whose TIF has elapsed
        for actor_id, acct in self._accounts.items():
            expired_ids: list[int] = []
            for oid, resting in list(acct.open_orders.items()):
                if resting.tif_steps > 0:
                    age = self._step - resting.placed_step
                    if age >= resting.tif_steps:
                        self._book.remove(resting)
                        self._emit_ack(actor_id, oid, AckStatus.EXPIRED)
                        expired_ids.append(oid)
            for oid in expired_ids:
                del acct.open_orders[oid]

        events = list(self._pending_events)
        self._pending_events.clear()

        return events

    # ------------------------------------------------------------------
    # Public API: observation builder
    # ------------------------------------------------------------------

    def observation(self, actor_id: str, n_levels: int = N_LEVELS) -> Observation:
        """Build a private Observation for the given actor.

        Top ``n_levels`` per side; thin books padded with ``size_lots=0``
        levels.  Trades since last snapshot.  Only the requesting actor's
        own acks/fills — no other actor's identity or state leaks (INV-11).
        """
        self._ensure_actor(actor_id)

        # Build bid levels
        bid_list: list[BookLevel] = []
        for price, total in self._book.bid_levels():
            if len(bid_list) >= n_levels:
                break
            bid_list.append(BookLevel(price_ticks=price, size_lots=total))
        # Pad to exactly n_levels
        while len(bid_list) < n_levels:
            # Convention: padded levels have price 0 and size 0
            bid_list.append(BookLevel(price_ticks=0, size_lots=0))

        # Build ask levels
        ask_list: list[BookLevel] = []
        for price, total in self._book.ask_levels():
            if len(ask_list) >= n_levels:
                break
            ask_list.append(BookLevel(price_ticks=price, size_lots=total))
        while len(ask_list) < n_levels:
            ask_list.append(BookLevel(price_ticks=0, size_lots=0))

        # Actor's own acks and fills, then clear the buffers
        own_acks = tuple(self._actor_acks.get(actor_id, []))
        own_fills = tuple(self._actor_fills.get(actor_id, []))
        self._actor_acks[actor_id] = []
        self._actor_fills[actor_id] = []

        trades = tuple(self._public_trades)

        obs = Observation(
            step=self._step,
            bids=tuple(bid_list),
            asks=tuple(ask_list),
            trades=trades,
            own_acks=own_acks,
            own_fills=own_fills,
        )
        return obs

    def clear_public_trades(self) -> None:
        """Clear the public trade buffer (call after all observations are built)."""
        self._public_trades.clear()

    # ------------------------------------------------------------------
    # Public API: ground_truth_view (harness-only — INV-11)
    # ------------------------------------------------------------------

    def ground_truth_view(self, actor_id: str) -> GroundTruthView:
        """Harness-only: true account state for validation.

        NEVER exposed through Observation — only for metrics/testing (INV-11).
        """
        self._ensure_actor(actor_id)
        acct = self._accounts[actor_id]
        return GroundTruthView(
            actor_id=actor_id,
            inventory_lots=acct.inventory_lots,
            cash=acct.cash,
            open_order_ids=tuple(sorted(acct.open_orders.keys())),
            fills=tuple(acct.fills),
        )

    # ------------------------------------------------------------------
    # Public API: step wrapper
    # ------------------------------------------------------------------

    @property
    def current_step(self) -> int:
        return self._step

    @property
    def book(self) -> OrderBook:
        """Direct book access — for tests and ground-truth queries only."""
        return self._book

    def step(
        self,
        background_events: list[tuple[str, ExchangeMessage]],
        agent_id: str,
        agent_action: ExchangeMessage | None = None,
    ) -> tuple[Observation, list[EngineEvent]]:
        """One full step: background events → snapshot → agent action → advance.

        Within one step:
        1. k background-actor events are applied in the deterministic order
           supplied by the caller (P2 provides them).
        2. One snapshot Observation is built for the agent.
        3. The agent's (at most one) action is applied.
        4. match_and_advance() expires TIF orders and bumps the step.

        Returns (observation_for_agent, all_engine_events).
        """
        # 1. Apply background events in caller-specified order
        for bg_actor, bg_msg in background_events:
            self.submit(bg_actor, bg_msg)

        # 2. Build observation for the agent BEFORE agent action
        obs = self.observation(agent_id)

        # 3. Apply agent action
        if agent_action is not None:
            self.submit(agent_id, agent_action)

        # 4. Advance
        events = self.match_and_advance()

        # Clear public trades for next step
        self.clear_public_trades()

        return obs, events
